services:
  db:
    image: postgres:17.5
    container_name: plexus-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}
